### ISSUE TITLE
Regarding "TranslatedLabel" of Weapon Components

### ISSUE THREAD

**Issue by Sainan** [DurtyFree/gta-v-data-dumps#59]
Even some really old ones like "component_pistol_varmod_luxe" are missing the "TranslatedLabel" property, even tho you can quite quickly find the answer in a decompiled script such as achievement_controller:
![image](https://user-images.githubusercontent.com/63328889/207693485-997e646e-f0c6-4782-8704-a54afd8e4fd9.png)
I'm guessing this is based on a manual list that you have as opposed to an automated process and your tooling is not open-source, so not like anyone can make a PR to resolve this.

**Comment by DurtyFree** [comment]
Hi there, thx for sharing - yes in most cases it completely automatically pulls all the data from the game files and not the scripts. I will enhance this.

Right now I am not able to open source the tooling because its part of my platform Pleb Masters: Forge - maybe in the future I will split this part of and make it open source

**Comment by DurtyFree** [comment]
Improved with latest commit, thx!
https://github.com/DurtyFree/gta-v-data-dumps/commit/741bb8c2f247f051d3854824ad3aebf293856192
